name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN || github.token }}
          enablement: true

      - uses: actions/upload-pages-artifact@v5
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v5
